app = "bitexly-frontend"
primary_region = "iad"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 80
min_machines_running = 0
processes = ["app"]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.serve]]
    # Serve the static build folder
    static_dir = "dist"

    # SPA fallback: any route not found serves index.html
    fallback_file = "dist/index.html"
